import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center min-h-screen bg-muted py-20">
        {/* <img src="/logo.png" alt="logo" className="h-20 m-auto" /> */}

        {children}
      </body>
    </html>
  );
}
