import { ThemeToggle } from "@/components/themetoggler";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center justify-center min-h-screen bg-muted py-20 relative">
        {children}
        <div className="fixed bottom-10 right-10">
          <ThemeToggle />
        </div>
      </body>
    </html>
  );
}
